[build]
  publish = ".next"
  command = "pnpm install --no-frozen-lockfile && pnpm run build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF backend/"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "10"


# Redirect all requests to Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API routes handling
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200


