[build]
  publish = ".next"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Redirect all requests to Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API routes handling
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Ignore backend directory for Netlify builds
[build.ignore]
  command = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF backend/"