[build]
  publish = ".next"
  command = "npm install --legacy-peer-deps && npm run build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF backend/ Frontend/"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_PACKAGE_MANAGER = "npm"

